### PR TITLE
Fix/tango light color

### LINKED ISSUE #169: Tango connection light intends connection error if successfully connected.
The connection light keeps red / turns red after few seconds, but the app is successfully connected to Tango:
- `rostopic echo tf ` shows device poses
- `rviz` shows fisheye image correctly
- log messages in the app confirm successful connection to Tango (see screenshot below).
screenshot_2017-03-07-14-54-07

### PR DESCRIPTION
**Pull request by PerrineAguiar**
This PR fixes #169.

### CODE REVIEW

File: TangoRosStreamer/app/src/main/java/eu/intermodalics/tango_ros_streamer/RunningActivity.java [hunk 1]
```diff
@@ -341,8 +341,10 @@ protected void init(NodeMainExecutor nodeMainExecutor) {
                         != TangoInitializationHelper.ARCH_ERROR) {
             mTangoRosNode = new TangoRosNode();
             mTangoRosNode.attachCallbackListener(this);
+
+            TangoInitializationHelper.checkTangoVersionOk(this);
             TangoInitializationHelper.bindTangoService(this, mTangoServiceConnection);
-            if (TangoInitializationHelper.checkTangoVersionOk(this)) {
+            if (TangoInitializationHelper.isTangoVersionOk()) {
```
Comment (mcopejans) [inline TangoRosStreamer/app/src/main/java/eu/intermodalics/tango_ros_streamer/RunningActivity.java]: I think the implementation of `checkTangoVersionOk` is confusing. It is not clear that it needs to be called for the `mTangoVersionOk` variable to be set. Can you make this a private function, rename to `testTangoVersionOk` and call it inside bindTangoService?

**Comment by jubeira** [comment]
So this happened because sometimes the `ServiceConnection` callback is called before checking the Tango version right? If that's the case, I think @mcopejans' suggestion sounds good; it also makes running the node a bit easier :+1:

**Comment by PerrineAguiar** [comment]
@mcopejans @jubeira Thanks for the review.
I addressed your comment.
