### PR TITLE
Fix/avoid empty occupancy grid when no subscriber

### LINKED ISSUE #345: avoid empty occupancy map if no subscriber

### PR DESCRIPTION
**Pull request by PerrineAguiar**
This PR adds two ROS parameters to enable/disable mesh and occupancy grid. That way we avoid relying on the number of subscribers to extract and publish them.

Fixes #345.

### CODE REVIEW

**Comment by PerrineAguiar** [comment]
@smits I added the check around the publish call.

**Comment by PerrineAguiar** [comment]
@smits ptal

File: tango_ros_common/tango_ros_native/src/tango_ros_node.cpp [hunk 1]
```diff
@@ -1120,11 +1129,12 @@ void TangoRosNode::PublishMesh() {
...
       }
       // Publish Tango mesh as occupancy grid.
-      if (occupancy_grid_publisher_.getNumSubscribers() > 0) {
+      if (enable_3dr_occupancy_grid_) {
         occupancy_grid_.data.clear();
         if (tango_3d_reconstruction_helper::ExtractFloorPlanImageAndConvertToOccupancyGrid(
             t3dr_context_, time_offset_, start_of_service_frame_id_,
-            t3dr_resolution_, t3dr_occupancy_grid_threshold_, &occupancy_grid_))
+            t3dr_resolution_, t3dr_occupancy_grid_threshold_, &occupancy_grid_) &&
+            occupancy_grid_publisher_.getNumSubscribers() > 0)
```
Comment (smits) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: Can we move the getNumSubscribers check around the Extract call, I guess if we are not going to publish it we don't need to extract the floorplan image?

File: tango_ros_common/tango_ros_native/src/tango_ros_node.cpp [hunk 2]
```diff
@@ -1103,12 +1110,14 @@ void TangoRosNode::PublishMesh() {
...
       }
       // Publish Tango mesh as visualization marker.
-      if (mesh_marker_publisher_.getNumSubscribers() > 0) {
+      if (enable_3dr_mesh_) {
         visualization_msgs::MarkerArray mesh_marker_array;
         tango_3d_reconstruction_helper::ExtractMeshAndConvertToMarkerArray(
             t3dr_context_, t3dr_updated_indices, time_offset_,
             start_of_service_frame_id_, &mesh_marker_array);
-        mesh_marker_publisher_.publish(mesh_marker_array);
+        if (mesh_marker_publisher_.getNumSubscribers() > 0) {
```
Comment (smits) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: Can we move this check around the Extract function? No need to extract anything as long as we are not publishing?

File: tango_ros_common/tango_ros_native/src/tango_ros_node.cpp (hunk 1 above)
Comment (PerrineAguiar) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: Yes we do. It can happen that there is no subscriber for the occupancy grid but we still want to extract it to be able to save it.

File: tango_ros_common/tango_ros_native/src/tango_ros_node.cpp (hunk 2 above)
Comment (PerrineAguiar) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: I agree that the case of the mesh is different since we don't need the data somewhere else. I will make the change.
