### PR TITLE
Fix/sync app and ros param

### LINKED ISSUE #221: Sync shared preferences with ros parameters when connecting to Tango

### LINKED ISSUE #224: ROS param and app UI inconsistency
When changing a parameter the ROS way, the UI doesn't show the updated version.
For example:
rospy.set_param("/tango/create_new_map", True)
rospy.set_param("/tango/localization_mode", 2)

The slider and drop-down menu are not updated on the app side.

### PR DESCRIPTION
**Pull request by PerrineAguiar**
Fixes #224.
Fixes #221.

It also fixes some errors regarding the GetMapUuids service.

### CODE REVIEW

File: tango_ros_common/tango_ros_common/src/main/java/eu/intermodalics/tango_ros_common/TangoServiceClientNode.java [hunk 1]
```diff
@@ -171,7 +171,7 @@ private Boolean getMapUuids() throws ServiceNotFoundException {
         ServiceClient<GetMapUuidsRequest, GetMapUuidsResponse> saveMapService =
                 mConnectedNode.newServiceClient(
                         NodeNamespaceHelper.BuildTangoRosNodeNamespaceName(GET_MAP_UUIDS_SRV_NAME),
-                        SaveMap._TYPE);
+                        GetMapUuids._TYPE);
```
Comment (smits) [inline tango_ros_common/tango_ros_common/src/main/java/eu/intermodalics/tango_ros_common/TangoServiceClientNode.java]: There seems to be mismatch here between saveMapService and GetMapUuids._TYPE?  Shouldn't `saveMapService` be renamed to `getMapUuidsService`?

**Comment by PerrineAguiar** [comment]
@smits Thanks for your review. I addressed your comments.
Here is the current behavior:
The preferences are set from the ROS params when:
* starting the app
* connecting to Tango
The ROS params are set from the app preferences when:
* pressing the RESTART TANGO button on the snackbar.

File: tango_ros_common/tango_ros_native/src/tango_ros_node.cpp [hunk 2]
```diff
@@ -35,15 +37,11 @@ std::vector<std::string> splitCommaSeparatedString(const std::string& comma_sepa
...
-          if (ss.peek() == ',')
-              ss.ignore();
-      }
-
-   return output;
+  std::string string_element;
+  while (std::getline(ss, string_element, ',')) {
+    output.push_back(string_element);
+  }
+  return output;
```
Comment (mcopejans) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: Sorry for making the whitespace error. FYI: Intermodalics style guide is 4 spaces :)

File: TangoRosStreamer/app/src/main/java/eu/intermodalics/tango_ros_streamer/ParameterNode.java [hunk 3]
```diff
@@ -81,4 +80,24 @@ public void uploadPreferencesToParameterServer() {
...
+    // Set app preferences according to ROS params.
+    public void setPreferencesFromParameterServer() {
+        SharedPreferences.Editor editor = mSharedPreferences.edit();
+        for (String paramName : mParamNames.keySet()) {
+            if (mParamNames.get(paramName) == "boolean") {
+                Boolean booleanValue = mConnectedNode.getParameterTree().getBoolean(NodeNamespaceHelper.BuildTangoRosNodeNamespaceName(paramName), false);
+                editor.putBoolean(paramName, booleanValue);
+            }
+            if (mParamNames.get(paramName) == "int_as_string") {
+                Integer intValue = mConnectedNode.getParameterTree().getInteger(NodeNamespaceHelper.BuildTangoRosNodeNamespaceName(paramName), 1);
```
Comment (mcopejans) [inline TangoRosStreamer/app/src/main/java/eu/intermodalics/tango_ros_streamer/ParameterNode.java]: Is there a reason for choosing 1 as default value instead of zero?

**Comment by PerrineAguiar** [comment]
@mcopejans Thanks for your review.

File: tango_ros_common/tango_ros_native/src/tango_ros_node.cpp (hunk 2 above)
Comment (smits) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: Actually it is 2 if I'm not mistaken, except for older projects that still use 4.

Comment (mcopejans) [inline tango_ros_common/tango_ros_native/src/tango_ros_node.cpp]: Oops, I still had an old code style file... Sorry :)
